In [64]:
import pandas as pd

In [65]:
data = pd.read_csv('diabetes.csv')

In [66]:
data.shape

(768, 9)

In [67]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [68]:
data.duplicated().sum()

0

In [69]:
X = data.drop('Outcome',axis=1)
y = data.Outcome

In [70]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y , test_size=0.3, random_state=42)

In [71]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train,y_train)

/opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [72]:
log_reg.coef_

array([[ 0.05654401,  0.03558455, -0.01087781, -0.00179055, -0.00098901,
         0.10761169,  0.52393868,  0.03582564]])

In [73]:
y_pred_trian = log_reg.predict(X_train)

In [74]:
y_pred_trian

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0])

In [75]:
pd.DataFrame({'Y_Actually':y_train , 'Y_Pred':y_pred_trian})

     Y_Actually  Y_Pred
334           0       0
139           0       0
485           1       0
547           0       0
18            0       0
..          ...     ...
71            0       0
106           0       0
270           1       1
435           1       1
102           0       0

[537 rows x 2 columns]

In [76]:
correct = 0 
for t,p in zip(y_train, y_pred_trian):
    if t==p:
        correct+=1
acc = correct / len(y_train)*100
acc

78.2122905027933

In [77]:
y_pred_test = log_reg.predict(X_test)

In [78]:
pd.DataFrame({'Y_Actually':y_test , 'Y_Pred':y_pred_test})

     Y_Actually  Y_Pred
668           0       0
324           0       0
624           0       0
690           0       0
473           0       0
..          ...     ...
619           1       0
198           1       0
538           0       0
329           0       0
302           0       0

[231 rows x 2 columns]

In [79]:
correct = 0 
for t,p in zip(y_test, y_pred_test):
    if t==p:
        correct+=1
acc = correct / len(y_test)*100
acc

74.02597402597402

In [80]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix,classification_report

In [81]:
accuracy_score(y_train, y_pred_trian)

0.7821229050279329

In [82]:
accuracy_score(y_test, y_pred_test)

0.7402597402597403

In [83]:
precision_score(y_test, y_pred_test)

0.625

In [84]:
recall_score(y_test, y_pred_test)

0.625

In [85]:
print(classification_report(y_train,y_pred_trian))

              precision    recall  f1-score   support

           0       0.80      0.89      0.84       349
           1       0.74      0.59      0.65       188

    accuracy                           0.78       537
   macro avg       0.77      0.74      0.75       537
weighted avg       0.78      0.78      0.78       537

In [86]:
data.Outcome.value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [87]:
Class_0 = data[data.Outcome==0].sample(268)

In [88]:
Class_1 = data[data.Outcome==1].sample(268)

In [89]:
balanced_data = pd.concat([Class_0,Class_1]).sample(268+268)

In [90]:
balanced_data.Outcome.value_counts()

1    268
0    268
Name: Outcome, dtype: int64

In [91]:
X = balanced_data.drop('Outcome',axis=1)
y = balanced_data.Outcome

In [92]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [93]:
lr = LogisticRegression()
lr.fit(X_train,y_train)

/opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [94]:
y_pred_train = lr.predict(X_train)

In [ ]:
accuracy_score(y_train,y_pred_train)

In [33]:
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.75      0.78      0.77       215
           1       0.77      0.74      0.75       213

    accuracy                           0.76       428
   macro avg       0.76      0.76      0.76       428
weighted avg       0.76      0.76      0.76       428

In [34]:
df = pd.read_csv('diabetes.csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [35]:
X  = df.drop('Outcome', axis=1)
y = df.Outcome

In [36]:
y.value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [12]:
!pip install imbalanced-learn

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Requirement already satisfied: imbalanced-learn in /home/4348cc34-6565-4da0-8cfe-d853b52489ea/.local/lib/python3.9/site-packages (0.12.4)
Requirement already satisfied: joblib>=1.1.1 in /home/4348cc34-6565-4da0-8cfe-d853b52489ea/.local/lib/python3.9/site-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: scikit-learn>=1.0.2 in /opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages (from imbalanced-learn) (1.0.2)
Requirement already satisfied: numpy>=1.17.3 in /opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages (from imbalanced-learn) (1.21.5)
Requirement already satisfied: scipy>=1.5.0 in /opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages (from imbalanced-learn) (1.7.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages (from imbalanced-learn) (2.2.0)

In [37]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(sampling_strategy = 'minority', random_state = 42 )
X,y = smote.fit_resample(X,y)

In [38]:
y.value_counts()

1    500
0    500
Name: Outcome, dtype: int64

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [40]:
lr = LogisticRegression()

In [41]:
lr.fit(X_train,y_train)

/opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [42]:
y_pred_train = lr.predict(X_train)

In [43]:
accuracy_score(y_train,y_pred_train)

0.74125

In [44]:
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.74      0.75      0.74       401
           1       0.75      0.73      0.74       399

    accuracy                           0.74       800
   macro avg       0.74      0.74      0.74       800
weighted avg       0.74      0.74      0.74       800

In [45]:
y_test_pred = lr.predict(X_test)
print(classification_report(y_test, y_test_pred))

              precision    recall  f1-score   support

           0       0.77      0.67      0.71        99
           1       0.71      0.80      0.75       101

    accuracy                           0.73       200
   macro avg       0.74      0.73      0.73       200
weighted avg       0.74      0.73      0.73       200

In [46]:
accuracy_score(y_test, y_test_pred)

0.735

In [47]:
df.corr()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898
Glucose,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581
BloodPressure,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068
SkinThickness,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752
Insulin,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548
BMI,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695
DiabetesPedigreeFunction,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844
Age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356
Outcome,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000

In [48]:
df = df.drop(['BloodPressure','SkinThickness'],axis=1)

In [49]:
df

,Pregnancies,Glucose,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,0,33.6,0.627,50,1
1,1,85,0,26.6,0.351,31,0
2,8,183,0,23.3,0.672,32,1
3,1,89,94,28.1,0.167,21,0
4,0,137,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...
763,10,101,180,32.9,0.171,63,0
764,2,122,0,36.8,0.340,27,0
765,5,121,112,26.2,0.245,30,0
766,1,126,0,30.1,0.349,47,1
767,1,93,0,30.4,0.315,23,0

In [46]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Requirement already satisfied: scikit-learn in /opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages (1.0.2)
Requirement already satisfied: scipy>=1.1.0 in /opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages (from scikit-learn) (1.7.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages (from scikit-learn) (2.2.0)
Requirement already satisfied: joblib>=0.11 in /home/4348cc34-6565-4da0-8cfe-d853b52489ea/.local/lib/python3.9/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: numpy>=1.14.6 in /opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages (from scikit-learn) (1.21.5)

In [50]:
from sklearn.preprocessing import MinMaxScaler

In [51]:
scaler = MinMaxScaler()

In [52]:
scaled_data = scaler.fit_transform(df)
scaled_data = pd.DataFrame(data=scaled_data, columns=df.columns)

In [53]:
scaled_data

,Pregnancies,Glucose,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.352941,0.743719,0.000000,0.500745,0.234415,0.483333,1.0
1,0.058824,0.427136,0.000000,0.396423,0.116567,0.166667,0.0
2,0.470588,0.919598,0.000000,0.347243,0.253629,0.183333,1.0
3,0.058824,0.447236,0.111111,0.418778,0.038002,0.000000,0.0
4,0.000000,0.688442,0.198582,0.642325,0.943638,0.200000,1.0
...,...,...,...,...,...,...,...
763,0.588235,0.507538,0.212766,0.490313,0.039710,0.700000,0.0
764,0.117647,0.613065,0.000000,0.548435,0.111870,0.100000,0.0
765,0.294118,0.608040,0.132388,0.390462,0.071307,0.150000,0.0
766,0.058824,0.633166,0.000000,0.448584,0.115713,0.433333,1.0
767,0.058824,0.467337,0.000000,0.453055,0.101196,0.033333,0.0

In [54]:
X= scaled_data.drop('Outcome', axis=1)
y = scaled_data.Outcome

In [55]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(sampling_strategy='minority', random_state=42)
X,y = smote.fit_resample(X,y)

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [57]:
lr_scaled = LogisticRegression()

In [58]:
lr_scaled.fit(X_train, y_train)

LogisticRegression()

In [59]:
y_pred_train = lr_scaled.predict(X_train)

In [61]:
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

         0.0       0.73      0.77      0.75       401
         1.0       0.76      0.71      0.74       399

    accuracy                           0.74       800
   macro avg       0.74      0.74      0.74       800
weighted avg       0.74      0.74      0.74       800

In [62]:
y_pred_test = lr_scaled.predict(X_test)

In [63]:
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

         0.0       0.73      0.72      0.72        99
         1.0       0.73      0.74      0.74       101

    accuracy                           0.73       200
   macro avg       0.73      0.73      0.73       200
weighted avg       0.73      0.73      0.73       200